fix fzf key binds

diff --git a/zsh/shortcuts b/zsh/shortcuts
--- a/zsh/shortcuts
+++ b/zsh/shortcuts
@@ -1,56 +1,58 @@
 #!/usr/bin/env bash
 
 # fzf edit recent file
-open-recent-edit-file () {
+open-recent-edit-file() {
   cwd=$(pwd)
   # select_file=$(find . -type f -not -path '*/.*' -exec ls -lt1 -- {} + \
   #   | sed 's|^\./||' \
   #   | fzf --height 40% --reverse \
   #   --header="cwd=$cwd  | cmd='$EDITOR <file>'  ")
-  select_file=$(\
+  select_file=$(
     fd . --type=file \
-    -E "*.png" \
-    -E "*.jpg" \
-    -E "*.jpeg" \
-    -E "*.mp3" \
-    -E "*.mp4" \
-    -E "*.docx" \
-    -E "*.doc" \
-    -E "*.xlsx" \
-    -E "*.wav" \
-    -E "*.gif" \
-    -E "*.psd" \
-    -E "*.pdf" \
-    -E "*.tiff" \
-    -E "*.avif" \
-    -E "*.jfif" \
-    -E "*.pjeg" \
-    -E "*.pjp" \
-    -E "*.svg" \
-    -E "*.wbep" \
-    -E "*.bmp" \
-    -E "*.ico" \
-    -E "*.cur" \
-    -E "*.tif" \
-    -E "*.mov" \
-    -E "*.avi" \
-    -E "*.wmv" \
-    -E "*.flv" \
-    -E "*.mkv" \
-    -E "*.webm" \
-    -E "*.aac" \
-    -E "*.flac" \
-    -E "*.aif" \
-    -E "*.m4a" \
-    -E "*.ogg" \
-    | xargs ls -1t \
-    | fzf --height 40% --reverse \
-    --header="cwd=$cwd  | cmd='$EDITOR <file>'  ")
+      -E "*.png" \
+      -E "*.jpg" \
+      -E "*.jpeg" \
+      -E "*.mp3" \
+      -E "*.mp4" \
+      -E "*.docx" \
+      -E "*.doc" \
+      -E "*.xlsx" \
+      -E "*.wav" \
+      -E "*.gif" \
+      -E "*.psd" \
+      -E "*.pdf" \
+      -E "*.tiff" \
+      -E "*.avif" \
+      -E "*.jfif" \
+      -E "*.pjeg" \
+      -E "*.pjp" \
+      -E "*.svg" \
+      -E "*.wbep" \
+      -E "*.bmp" \
+      -E "*.ico" \
+      -E "*.cur" \
+      -E "*.tif" \
+      -E "*.mov" \
+      -E "*.avi" \
+      -E "*.wmv" \
+      -E "*.flv" \
+      -E "*.mkv" \
+      -E "*.webm" \
+      -E "*.aac" \
+      -E "*.flac" \
+      -E "*.aif" \
+      -E "*.m4a" \
+      -E "*.ogg" |
+      xargs ls -1t |
+      fzf --height 40% --reverse \
+        --header="cwd=$cwd  | cmd='$EDITOR <file>'  "
+  )
   if [ -z $select_file ]; then
     zle reset-prompt
     return
   fi
-  [ ! -z $select_file ] && print -s $EDITOR $select_file ; $EDITOR $select_file
+  [ ! -z $select_file ] && print -s $EDITOR $select_file
+  $EDITOR $select_file
   [ ! -z $select_file ] && echo "$EDITOR $select_file"
   cd $cwd
   zle accept-line
@@ -59,8 +61,8 @@ zle -N open-recent-edit-file
 bindkey '^f' open-recent-edit-file
 
 open-recent-cd() {
-  selected_dir=$(fd --type=d --exclude node_modules \
-    | fzf --height 40% --reverse)
+  selected_dir=$(fd --type=d --exclude node_modules |
+    fzf --height 40% --reverse)
   if [ -z $selected_dir ]; then
     zle reset-prompt
     return
@@ -71,30 +73,41 @@ open-recent-cd() {
 }
 
 zle -N open-recent-cd
-bindkey '^t' open-recent-cd
+bindkey '^y' open-recent-cd
 
-zoxide-jump () {
-  # Assign the result of zoxide and fzf to a variable
-  local dir="$(zoxide query --list | fzf --height 40% --reverse)"
-  # Check if the directory string is non-empty
-  if [[ -z "$dir" ]]; then
-    # If it is empty, reset the prompt and return
-    zle reset-prompt
-    return
-  fi
-  if [[ -d "$dir" ]]; then
-    # If the directory exists, change to it
-    tmux new-window -c "$dir"
-  else
-    # If the directory does not exist, print an error message
-    echo "Directory not found: $dir"
-  fi
-  zle accept-line
+fzf-file-widget() {
+  LBUFFER="${LBUFFER}$(fd --type f | fzf --height 40% --reverse)"
+  local ret=$?
+  zle reset-prompt
+  return $ret
 }
-# autoload -U zoxide-jump
-zle -N zoxide-jump
-bindkey '^z' zoxide-jump
 
+zle -N fzf-file-widget
+bindkey -M vicmd '^T' fzf-file-widget
+bindkey -M viins '^T' fzf-file-widget
+
+# zoxide-jump() {
+#   # Assign the result of zoxide and fzf to a variable
+#   local dir="$(zoxide query --list | fzf --height 40% --reverse)"
+#   # Check if the directory string is non-empty
+#   if [[ -z "$dir" ]]; then
+#     # If it is empty, reset the prompt and return
+#     zle reset-prompt
+#     return
+#   fi
+#   if [[ -d "$dir" ]]; then
+#     # If the directory exists, change to it
+#     tmux new-window -c "$dir"
+#   else
+#     # If the directory does not exist, print an error message
+#     echo "Directory not found: $dir"
+#   fi
+#   zle accept-line
+# }
+# # autoload -U zoxide-jump
+# zle -N zoxide-jump
+# bindkey '^z' zoxide-jump
+#
 # tmux-sessionor
 # In ~/.zshrc
 # tmux-sessionor widget
@@ -115,4 +128,3 @@ bindkey '^z' zoxide-jump
 # }
 # zle -N sessionor
 # bindkey '^g' sessionor
-
